[package]
name = "asset_modifer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.glfw]
version = "0.53.0"
default-features = false
