use thiserror::Error;

#[derive(Debug, Error)]
#[allow(non_camel_case_types)]
pub enum ShaderErrors {
  #[error("Shader is not a value generated by OpenGL or maxLength is less than 0.")]
  GL_INVALID_VALUE,
  #[error("Shader is not a value generated by OpenGL.")]
  GL_INVALID_OPERATION,
  #[error("No uniform was found matching the name.")]
  UniformLocationNotFound
}